### ISSUE TITLE
Dependencies for Linux don't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by mark-summerfield** [PySide/pyside2#91] opened 2016-06-08 06:25 UTC
When I tried the second apt-get install it failed saying there is no package called libqt5quickwidgets5.

Also the first apt-get specifieds python-dev (which is Python 2.7) and doesn't mention python3-dev which is what I've used.

**Comment by ethanhs** [comment] 2016-06-08 18:12
This is a duplicate of https://github.com/PySide/pyside2-setup/issues/42 , let's focus the conversation over there.

**Closed by ethanhs** 2016-06-08 18:12 UTC
